log:
  mode: on
  stdout:
    level: warn
  file:
    level: info
#    path: ~/.cache/taro/taro.log
  syslog:
    level: off # Not yet implemented

persistence:
  enabled: true
  type: sqlite
  max_records: -1
#  max_age: #ISO 8601 duration format
#  database: ~/.local/share/taro/taro.db

plugins: []
#plugins: ['taro_sns']

default_action: --help